/**
 * Report footer: "Generated by [name] on [date]".
 * Rendered at the bottom of the report (preview, print, PDF).
 */
export default function ReportFooter({ generatedBy, generatedAt }) {
  const dateStr = generatedAt
    ? new Date(generatedAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })
    : new Date().toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });

  if (!generatedBy && !generatedAt) return null;

  return (
    <div className="report-footer" data-report-footer>
      Generated by <strong>{generatedBy || "—"}</strong> on {dateStr}
    </div>
  );
}
