import { useState, useRef } from "react";
import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import ReportHeader from "./ReportHeader";
import ReportFooter from "./ReportFooter";
import "./ReportModal.css";

const IconClose = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

/**
 * ReportModal: open a modal to filter and generate a report with professional header.
 * Props:
 *   open, onClose
 *   reportTitle - e.g. "Asset Report"
 *   generatedBy - user name for "Generated by X"
 *   renderFilters - () => ReactNode (filter form)
 *   getReportData - () => ({ rows: Array<Object>, columns: Array<{ key, label }> })
 */
export default function ReportModal({
  open,
  onClose,
  reportTitle = "Report",
  generatedBy = "",
  generatedAt: generatedAtProp,
  renderFilters,
  getReportData,
}) {
  const [step, setStep] = useState("filters"); // "filters" | "preview"
  const [reportData, setReportData] = useState(null);
  const [generatedAt, setGeneratedAt] = useState(null);
  const [pdfLoading, setPdfLoading] = useState(false);
  const reportRef = useRef(null);

  if (!open) return null;

  const handleGenerate = () => {
    try {
      const data = getReportData();
      setReportData(data);
      setGeneratedAt(new Date().toISOString());
      setStep("preview");
    } catch (e) {
      console.error(e);
    }
  };

  const handleBack = () => {
    setStep("filters");
    setReportData(null);
    setGeneratedAt(null);
  };

  const handlePrint = () => {
    if (!reportRef.current) return;
    const printWindow = window.open("", "_blank");
    const styles = `
      body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 24px; color: #0f172a; }
      .report-header { margin-bottom: 24px; }
      .report-header-top { display: flex; justify-content: space-between; align-items: flex-start; flex-wrap: wrap; gap: 16px; }
      .report-header-brand { display: flex; flex-direction: column; gap: 4px; }
      .report-header-logo { width: 48px; height: 48px; object-fit: contain; }
      .report-header-company { font-size: 1.25rem; font-weight: 800; color: #0ea5e9; letter-spacing: 0.02em; }
      .report-header-contact { text-align: right; font-size: 0.8rem; color: #475569; line-height: 1.6; }
      .report-header-contact span { margin-left: 6px; }
      .report-header-bar { height: 6px; display: flex; margin-top: 16px; border-radius: 0 0 4px 4px; overflow: hidden; }
      .report-header-bar-left { flex: 0 0 65%; background: #0ea5e9; }
      .report-header-bar-right { flex: 1; background: #0c4a6e; }
      .report-footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 0.8rem; color: #64748b; }
      .report-footer strong { color: #334155; }
      table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 0.85rem; }
      th, td { border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }
      th { background: #f1f5f9; font-weight: 600; color: #334155; }
      tr:nth-child(even) { background: #f8fafc; }
    `;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head><title>${reportTitle}</title><style>${styles}</style></head>
        <body>${reportRef.current.innerHTML}</body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  const handleDownloadPdf = () => {
    if (!reportRef.current) return;
    setPdfLoading(true);
    const el = reportRef.current;
    html2canvas(el, { scale: 2, useCORS: true, logging: false })
      .then((canvas) => {
        const imgData = canvas.toDataURL("image/png");
        const pdf = new jsPDF("p", "mm", "a4");
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
        const imgWidth = pdfWidth;
        const imgHeight = (canvas.height * pdfWidth) / canvas.width;
        const totalPages = Math.ceil(imgHeight / pdfHeight) || 1;
        for (let i = 0; i < totalPages; i++) {
          if (i > 0) pdf.addPage();
          pdf.addImage(imgData, "PNG", 0, -i * pdfHeight, imgWidth, imgHeight);
        }
        const fileName = `${String(reportTitle).replace(/\s+/g, "_")}.pdf`;
        pdf.save(fileName);
      })
      .catch((err) => console.error("PDF export failed:", err))
      .finally(() => setPdfLoading(false));
  };

  const columns = reportData?.columns || [];
  const rows = reportData?.rows || [];

  return (
    <div className="report-modal-overlay" onClick={onClose}>
      <div className="report-modal" onClick={(e) => e.stopPropagation()}>
        <div className="report-modal-header">
          <h2 className="report-modal-title">
            {step === "filters" ? `Generate ${reportTitle}` : reportTitle}
          </h2>
          <button type="button" className="report-modal-close" aria-label="Close" onClick={onClose}>
            <IconClose />
          </button>
        </div>
        <div className="report-modal-body">
          {step === "filters" && (
            <>
              <div className="report-modal-filters">
                {typeof renderFilters === "function" ? renderFilters() : null}
              </div>
              <div className="report-modal-actions">
                <button type="button" className="entity-btn entity-btn--secondary" onClick={onClose}>
                  Cancel
                </button>
                <button type="button" className="entity-btn entity-btn--primary" onClick={handleGenerate}>
                  Generate report
                </button>
              </div>
            </>
          )}
          {step === "preview" && (
            <>
              <div className="report-preview-wrap" ref={reportRef}>
                <ReportHeader
                  generatedBy={generatedBy}
                  generatedAt={generatedAt}
                  showGenerated={false}
                />
                <div className="report-preview-table-wrap">
                  <table className="report-preview-table">
                    <thead>
                      <tr>
                        {columns.map((col) => (
                          <th key={col.key}>{col.label}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {rows.map((row, i) => (
                        <tr key={i}>
                          {columns.map((col) => (
                            <td key={col.key}>{row[col.key] != null ? String(row[col.key]) : "—"}</td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <ReportFooter generatedBy={generatedBy} generatedAt={generatedAt} />
              </div>
              <div className="report-modal-actions">
                <button type="button" className="entity-btn entity-btn--secondary" onClick={handleBack}>
                  Back to filters
                </button>
                <button type="button" className="entity-btn entity-btn--secondary" onClick={handlePrint}>
                  Print
                </button>
                <button type="button" className="entity-btn entity-btn--primary" onClick={handleDownloadPdf} disabled={pdfLoading}>
                  {pdfLoading ? "Preparing…" : "Download PDF"}
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
